server:
  port: 8762

spring:
  application:
    name: springcloud-privater
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/